"""Testing utilities for evaluating ROI-VFC pipeline on downstream tasks.

This module focuses on evaluation metrics for detection/segmentation models that
consume transferred features generated by ROI-VFC + FeatureSpaceTransfer.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, Mapping, Optional

import torch
import torch.nn.functional as F

from .train_roi_vfc import (
    _extract_first_tensor,
    _normalize_temporal_labels,
    _safe_reset_roi_buffer,
    _to_device,
)


Tensor = torch.Tensor


def evaluate_roi_vfc_downstream(
    roi_vfc: torch.nn.Module,
    feature_extractor: torch.nn.Module,
    feature_space_transfer: torch.nn.Module,
    dataloader: Iterable[Dict[str, Any]],
    downstream_models: Mapping[str, torch.nn.Module],
    device: Optional[torch.device] = None,
    task_criteria: Optional[Mapping[str, Callable[[Any, Any], Tensor]]] = None,
    metric_fns: Optional[Mapping[str, Callable[[Any, Any], Dict[str, float]]]] = None,
) -> Dict[str, float]:
    """Evaluate trained pipeline on downstream tasks.

    Returns averaged metrics across test batches. If no custom metric is
    provided for a task, this function reports:
      - `<task>_consistency_mse`: MSE(pred(original_feature), pred(transferred_feature))
      - `<task>_loss`: criterion(pred(transferred_feature), target) when possible
    """
    if device is None:
        device = next(roi_vfc.parameters()).device

    task_criteria = task_criteria or {}
    metric_fns = metric_fns or {}

    roi_vfc.eval()
    feature_extractor.eval()
    feature_space_transfer.eval()
    for model in downstream_models.values():
        model.eval()

    total: Dict[str, float] = {"num_steps": 0.0}

    with torch.no_grad():
        for batch in dataloader:
            batch = _to_device(batch, device)
            frames = batch["frames"]  # [B, T, C, H, W]
            frame_mask = batch.get("frame_mask")
            labels_seq_batch = batch.get("labels", [])

            if frame_mask is None:
                frame_mask = torch.ones(frames.size(0), frames.size(1), dtype=torch.bool, device=frames.device)

            for b in range(frames.size(0)):
                _safe_reset_roi_buffer(roi_vfc)
                labels_seq = labels_seq_batch[b] if isinstance(labels_seq_batch, list) and len(labels_seq_batch) > b else []

                for t in range(frames.size(1)):
                    if not bool(frame_mask[b, t].item()):
                        continue

                    frame_t = frames[b : b + 1, t]
                    labels_t = _normalize_temporal_labels(labels_seq, t)

                    source_features = feature_extractor(frame_t)
                    roi_output = roi_vfc(source_features)
                    transfer_output = feature_space_transfer(roi_output["F_cur_hat"])
                    transferred_features = transfer_output[0] if isinstance(transfer_output, (tuple, list)) else transfer_output

                    for task_name, model in downstream_models.items():
                        pred_src = model(source_features)
                        pred_new = model(transferred_features)

                        src_t = _extract_first_tensor(pred_src)
                        new_t = _extract_first_tensor(pred_new)
                        if src_t is not None and new_t is not None:
                            key = f"{task_name}_consistency_mse"
                            total[key] = total.get(key, 0.0) + float(F.mse_loss(new_t, src_t).item())

                        # custom metric hook
                        if task_name in metric_fns:
                            target = labels_t.get(task_name) if isinstance(labels_t, dict) else None
                            metric_values = metric_fns[task_name](pred_new, target)
                            for mk, mv in metric_values.items():
                                k = f"{task_name}_{mk}"
                                total[k] = total.get(k, 0.0) + float(mv)
                        elif task_name in task_criteria:
                            target = None
                            if task_name == "segmentation" and isinstance(labels_t, dict):
                                if torch.is_tensor(labels_t.get("segmentation_mask")):
                                    target = labels_t["segmentation_mask"].unsqueeze(0)
                            elif isinstance(labels_t, dict) and torch.is_tensor(labels_t.get(task_name)):
                                target = labels_t[task_name].unsqueeze(0)

                            if target is not None:
                                task_loss = task_criteria[task_name](pred_new, target)
                                key = f"{task_name}_loss"
                                total[key] = total.get(key, 0.0) + float(task_loss.item())

                    total["num_steps"] += 1.0

    n = max(total.get("num_steps", 0.0), 1.0)
    return {k: (v / n if k != "num_steps" else v) for k, v in total.items()}
