experiment_name: roi_vfc_deeplabv3_vspw_codec_bitrate16
seed: 42

model:
  roi_vfc:
    img_channels: 3
    feat_channels: 64
    y_chan: 96
    lambda_rd: 0.01
  feature_extraction:
    backbone: resnet50
    pretrained: true
    freeze: true
  perception_extraction:
    backbone: resnet50
    pretrained: true
    remove_res1: true
    freeze: true
  feature_space_transfer:
    in_channel: 256
    mid_channel: 64
  deeplabv3:
    backbone: resnet50
    pretrained: true
    weights_path: outputs/deeplabv3_vspw_resnet50/deeplabv3_resnet50_best.pt
    freeze: true
    aux_weight: 0.4

data:
  dataset_name: vspw
  data_root: data/VSPW
  train_split: train
  valid_split: valid
  image_size: [128, 128]
  spatial_transform: crop   # crop | resize
  train_crop_type: random   # random | center
  valid_crop_type: center   # random | center
  pad_if_needed: true
  max_train_samples: null
  max_valid_samples: 1000
  seq_len: 8
  num_classes: 125

training:
  epochs: 30
  resume_from: null
  train_batch_size: 4
  valid_batch_size: 1
  lr: 1.0e-4
  weight_decay: 1.0e-4
  num_workers: 8
  device: auto
  print_freq: 20
  stages:
    - name: codec_stage_1
      optimize: codec
      epochs: 4
      lr: 1.0e-4
      weight_decay: 1.0e-4
      codec:
        rate_scale: 0.5
        include_rz: false
    - name: codec_stage_2
      optimize: codec
      epochs: 4
      lr: 1.0e-4
      weight_decay: 1.0e-4
      codec:
        rate_scale: 0.5
        include_rz: true
    - name: codec_stage_3
      optimize: codec
      epochs: 4
      lr: 1.0e-4
      weight_decay: 1.0e-4
      codec:
        rate_scale: 1.0
        include_rz: true
    - name: codec_stage_4
      optimize: codec
      epochs: 4
      lr: 5.0e-5
      weight_decay: 1.0e-4
      codec:
        rate_scale: 1.0
        include_rz: true
    - name: codec_stage_5
      optimize: codec
      epochs: 4
      lr: 1.0e-5
      weight_decay: 1.0e-4
      codec:
        rate_scale: 1.0
        include_rz: true
    - name: fst_stage_1
      optimize: fst
      epochs: 10
      lr: 1.0e-5
      weight_decay: 1.0e-4
      codec:
        rate_scale: 1.0
        include_rz: true

loss_weights:
  codec:
    lambda_r: 16.0
    lambda_f: 16.0
    lambda_c: 1.6
    lambda_p: 4.0
  fst:
    lambda_task: 10.0
    lambda_x: 1024.0
    lambda_mid: 16.0
    lambda_high: 64.0

logging:
  use_tqdm: true
  log_batch_metrics: true
  batch_log_interval: 1
  comet:
    enabled: true
    api_key: mkfmxVIjacb8h74qKO6NzPdPN
    experiment_key: null
    project_name: roi-vfc
    workspace: dangdinh17

output:
  save_dir: outputs/roi_vfc_deeplabv3_vspw_codec_bitrate16
  save_every_epoch: true
